"""empty message

Revision ID: 05f7db87fdb3
Revises: dcd78969e47c
Create Date: 2022-03-23 21:21:56.095438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f7db87fdb3'
down_revision = 'dcd78969e47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweedle_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('one_attempt_wins', sa.Integer(), nullable=True),
    sa.Column('two_attempt_wins', sa.Integer(), nullable=True),
    sa.Column('three_attempt_wins', sa.Integer(), nullable=True),
    sa.Column('four_attempt_wins', sa.Integer(), nullable=True),
    sa.Column('five_attempt_wins', sa.Integer(), nullable=True),
    sa.Column('six_attempt_wins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweedle_scores')
    # ### end Alembic commands ###
